# Generated by Django 4.1.7 on 2023-04-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coursestepuserprogress",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="coursestepuserprogress",
            name="step",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="db.coursestep",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="coursestepuserprogress",
            unique_together={("user", "step", "course")},
        ),
        migrations.RemoveField(
            model_name="coursestepuserprogress",
            name="component",
        ),
    ]
