# Generated by Django 4.1.7 on 2023-03-21 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_coursestep_evaluation_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursestep",
            name="is_self_evaluated",
        ),
        migrations.RemoveField(
            model_name="coursestep",
            name="requires_file",
        ),
        migrations.RemoveField(
            model_name="coursestep",
            name="requires_manual_review",
        ),
        migrations.RemoveField(
            model_name="coursestep",
            name="requires_test",
        ),
    ]
