# Generated by Django 4.1.7 on 2023-03-19 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_fileevaluation_fileresource_evaluationattempt"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FileEvaluation",
            new_name="FileEvaluationType",
        ),
    ]
