# Generated by Django 4.1.7 on 2023-03-13 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_courseenrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TEST", "Test"),
                            ("EXTERNAL_RESOURCE", "External Resource"),
                            ("UNKNOWN", "Unknown step"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CourseStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField()),
                ("requires_file", models.BooleanField(default=False)),
                ("requires_test", models.BooleanField(default=False)),
                ("requires_manual_review", models.BooleanField(default=True)),
                ("is_self_evaluated", models.BooleanField(default=False)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.coursecomponent",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.course"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("course", "component"), ("course", "order")},
            },
        ),
    ]
