# Generated by Django 4.1.7 on 2023-03-23 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_remove_coursestep_is_self_evaluated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="author",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
