# Generated by Django 4.1.7 on 2023-03-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_coursecomponent_coursestep"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseComponentResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="coursecomponent",
            name="resources",
            field=models.ManyToManyField(blank=True, to="db.coursecomponentresource"),
        ),
    ]
