# Generated by Django 4.1.7 on 2023-03-23 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_course_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="author",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrolled_students",
                to="db.course",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseenrollment",
            unique_together={("course", "user")},
        ),
    ]
