# Generated by Django 4.1.7 on 2023-04-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_remove_coursestepuserprogress_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationattempt",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
