# Generated by Django 4.1.7 on 2023-04-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0005_alter_evaluationattempt_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursestepuserprogress",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.coursestep"
            ),
        ),
    ]
