# Generated by Django 4.1.7 on 2023-03-24 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0005_alter_course_author_alter_courseenrollment_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursestep",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="db.course",
            ),
        ),
        migrations.AlterField(
            model_name="coursestepusercompletion",
            name="completed_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="coursestepusercompletion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_steps_completion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
