# Generated by Django 4.1.7 on 2023-04-04 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shared.enums
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0006_alter_coursestepuserprogress_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("file", models.FileField(upload_to="uploads/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "WAITING"),
                            ("SUBMITTED", "SUBMITTED"),
                            ("FAILED", "FAILED"),
                            ("PASSED", "PASSED"),
                        ],
                        default=shared.enums.CourseStepEvaluationStatus["WAITING"],
                        max_length=40,
                    ),
                ),
                (
                    "course_step",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="db.coursestep",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="coursestepuserprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="EvaluationAttempt",
        ),
    ]
