# Generated by Django 4.1.7 on 2023-03-14 22:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0007_exercise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursecomponent",
            name="resources",
        ),
    ]
