# Generated by Django 4.1.7 on 2023-04-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0007_submission_alter_coursestepuserprogress_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursestepuserprogress",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
