# Generated by Django 4.1.7 on 2023-03-14 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0008_remove_coursecomponent_resources"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CourseComponentResource",
            new_name="LinkResource",
        ),
    ]
