# Generated by Django 4.1.7 on 2023-03-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0009_rename_coursecomponentresource_linkresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="resources",
            field=models.ManyToManyField(blank=True, to="db.linkresource"),
        ),
    ]
