# Generated by Django 4.1.7 on 2023-03-24 12:34

from django.db import migrations, models
import shared.enums


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0009_alter_evaluation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("COURSE_STEP_EVALUATION_STATUS", "_PREFIX"),
                    ("WAITING", "WAITING"),
                    ("SUBMITTED", "SUBMITTED"),
                    ("PASSED", "PASSED"),
                    ("SKIPPED", "SKIPPED"),
                    ("UNKNOWN", "UNKNOWN"),
                ],
                default=shared.enums.CourseStepEvaluationStatus["UNKNOWN"],
                max_length=40,
            ),
        ),
    ]
