# Generated by Django 4.1.7 on 2023-03-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0010_evaluationattempt_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evaluationattempt",
            name="is_passed",
        ),
        migrations.AddField(
            model_name="evaluationattempt",
            name="evaluation",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="db.evaluation",
            ),
            preserve_default=False,
        ),
    ]
