# Generated by Django 4.1.7 on 2023-03-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("db", "0010_exercise_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursestep",
            name="step_content_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="coursestep",
            name="step_object_id",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
