# Generated by Django 4.1.7 on 2023-03-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("db", "0011_coursestep_step_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursestep",
            name="step_content_type",
            field=models.ForeignKey(
                default=None,
                limit_choices_to={"model__in": ("exercise",)},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
