# Generated by Django 4.1.7 on 2023-03-24 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0011_remove_evaluationattempt_is_passed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationattempt",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="db.fileresource",
            ),
        ),
    ]
