# Generated by Django 4.1.7 on 2023-03-15 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("db", "0014_coursestepusercompletion"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coursestep",
            unique_together={
                ("course", "step_content_type", "step_object_id"),
                ("course", "order"),
            },
        ),
        migrations.DeleteModel(
            name="CourseComponentCompletion",
        ),
        migrations.RemoveField(
            model_name="coursestep",
            name="component",
        ),
    ]
