# Generated by Django 4.1.7 on 2023-03-24 21:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0015_remove_evaluationattempt_course_step_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseComponent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("resources", models.ManyToManyField(blank=True, to="db.linkresource")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="coursestep",
            unique_together={("course", "order")},
        ),
        migrations.AddField(
            model_name="coursestep",
            name="component",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="db.coursecomponent",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursestep",
            unique_together={("course", "component"), ("course", "order")},
        ),
        migrations.RemoveField(
            model_name="coursestep",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="coursestep",
            name="object_uuid",
        ),
    ]
