# Generated by Django 4.1.7 on 2023-03-24 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0018_delete_evaluation_coursestepusercompletion_component_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coursestepusercompletion",
            unique_together={("user", "component", "course")},
        ),
        migrations.RemoveField(
            model_name="coursestepusercompletion",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="coursestepusercompletion",
            name="object_uuid",
        ),
    ]
