# Generated by Django 4.1.7 on 2023-03-24 22:06

from django.db import migrations, models
import shared.enums


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0019_alter_coursestepusercompletion_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecomponent",
            name="type",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "UNKNOWN"),
                    ("EXERCISE", "EXERCISE"),
                    ("FILE_EVALUATION", "FILE_EVALUATION"),
                    ("TEST_EVALUATION", "TEST_EVALUATION"),
                    ("TEACHER_EVALUATION", "TEACHER_EVALUATION"),
                ],
                default=shared.enums.CourseStepComponentTypes["UNKNOWN"],
                max_length=40,
            ),
        ),
    ]
