# Generated by Django 4.1.7 on 2023-03-24 23:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0021_alter_coursestep_evaluation_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalResource",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("url", models.URLField()),
                ("file", models.FileField(upload_to="uploads/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="LinkResource",
        ),
        migrations.AlterField(
            model_name="coursecomponent",
            name="resources",
            field=models.ManyToManyField(blank=True, to="db.externalresource"),
        ),
    ]
