# Generated by Django 4.1.7 on 2023-03-24 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0022_externalresource_delete_linkresource_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationattempt",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="db.externalresource",
            ),
        ),
        migrations.DeleteModel(
            name="FileResource",
        ),
    ]
