# Generated by Django 4.1.7 on 2023-03-27 17:01

from django.db import migrations, models
import django.db.models.deletion
import shared.enums


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0023_alter_evaluationattempt_file_delete_fileresource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecomponent",
            name="type",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "UNKNOWN"),
                    ("EXERCISE", "EXERCISE"),
                    ("FILE_EVALUATION", "FILE_EVALUATION"),
                ],
                default=shared.enums.CourseStepComponentTypes["UNKNOWN"],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="db.course",
            ),
        ),
    ]
