# Generated by Django 4.1.7 on 2023-03-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0024_alter_coursecomponent_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalresource",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
