# Generated by Django 4.1.7 on 2023-03-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0025_alter_externalresource_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalresource",
            name="type",
            field=models.CharField(
                choices=[("FILE", "File"), ("URL", "URL")],
                default="FILE",
                max_length=50,
            ),
        ),
    ]
