runtime: python310

entrypoint: gunicorn -c gunicorn.conf.py --threads 4 server.wsgi:application

instance_class: F2

handlers:
  - url: /static
    static_dir: staticfiles-cdn/

  - url: /media
    static_dir: media/

  - url: /.*
    script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.5