# Generated by Django 4.1.7 on 2023-03-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_tracker", "0002_course_created_at_course_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("requires_file", models.BooleanField(default=False)),
                ("requires_test", models.BooleanField(default=False)),
                ("requires_manual_review", models.BooleanField(default=False)),
                ("is_self_evaluated", models.BooleanField(default=False)),
                (
                    "file_solution",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("test_solution", models.TextField(blank=True)),
                (
                    "resources",
                    models.ManyToManyField(blank=True, to="course_tracker.resource"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
