# Generated by Django 4.1.7 on 2023-03-05 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_tracker", "0003_resource_exercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_tracker.course",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_tracker.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("course", "exercise")},
            },
        ),
    ]
