# Generated by Django 4.1.7 on 2023-03-05 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course_tracker", "0007_course_exercises"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEnrolment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_tracker.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="exercisecompletion",
            unique_together={("user", "exercise")},
        ),
        migrations.DeleteModel(
            name="Enrolment",
        ),
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                through="course_tracker.CourseEnrolment", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
