# Generated by Django 4.1.7 on 2023-03-05 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_tracker", "0008_courseenrolment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courseenrolment",
            old_name="student",
            new_name="user",
        ),
    ]
