# Generated by Django 4.1.7 on 2023-03-05 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_tracker", "0011_remove_course_exercises"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courseexercise",
            unique_together={("course", "exercise", "order")},
        ),
    ]
