# Generated by Django 4.1.7 on 2023-03-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_tracker", "0013_alter_courseexercise_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciseattempt",
            name="quiz_solution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course_tracker.quizsolution",
            ),
        ),
    ]
