# Generated by Django 4.1.7 on 2023-03-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_tracker", "0014_alter_exerciseattempt_quiz_solution"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisecompletion",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="exerciseattempt",
            name="quiz_solution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course_tracker.quizsolution",
            ),
        ),
        migrations.AlterField(
            model_name="exercisecompletion",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
