# Generated by Django 4.1.7 on 2023-03-08 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_tracker", "0019_rename_description_resource_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CourseExercise",
            new_name="CourseStepOrder",
        ),
    ]
