# Generated by Django 4.1.7 on 2023-03-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "course_tracker",
            "0022_coursestep_rename_learningstep_coursecomponent_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursecomponent",
            name="is_self_evaluated",
        ),
        migrations.RemoveField(
            model_name="coursecomponent",
            name="requires_file",
        ),
        migrations.RemoveField(
            model_name="coursecomponent",
            name="requires_manual_review",
        ),
        migrations.RemoveField(
            model_name="coursecomponent",
            name="requires_test",
        ),
        migrations.AddField(
            model_name="coursestep",
            name="is_self_evaluated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coursestep",
            name="requires_file",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coursestep",
            name="requires_manual_review",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="coursestep",
            name="requires_test",
            field=models.BooleanField(default=False),
        ),
    ]
