# Generated by Django 4.1.7 on 2023-03-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_tracker", "0024_coursecomponentcompletion_delete_exercisecompletion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecomponent",
            name="type",
            field=models.CharField(
                choices=[
                    ("TEST", "Test"),
                    ("EXTERNAL_RESOURCE", "External Resource"),
                    ("UNKNOWN", "Unknown step"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
    ]
