# Generated by Django 4.1.7 on 2023-03-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_tracker", "0006_exercisecompletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="exercises",
            field=models.ManyToManyField(to="course_tracker.exercise"),
        ),
    ]
