# Generated by Django 4.1.7 on 2023-03-05 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_tracker", "0010_rename_courseenrolment_courseenrollment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="exercises",
        ),
    ]
