# Generated by Django 4.1.7 on 2023-03-08 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_tracker", "0015_exercisecompletion_is_completed_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Exercise",
            new_name="CourseStep",
        ),
    ]
