# Generated by Django 4.1.7 on 2023-03-08 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course_tracker", "0020_rename_courseexercise_coursesteporder"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_tracker.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RenameModel(
            old_name="CourseStep",
            new_name="LearningStep",
        ),
        migrations.DeleteModel(
            name="CourseStepOrder",
        ),
        migrations.AddField(
            model_name="courseitem",
            name="learning_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_tracker.learningstep",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseitem",
            unique_together={("course", "order"), ("course", "learning_step")},
        ),
    ]
