# class Exercise(models.Model):
#     title = models.CharField(max_length=100)
#     description = models.TextField()
#     requires_file = models.BooleanField(default=False)
#     requires_test = models.BooleanField(default=False)
#     requires_manual_review = models.BooleanField(default=False)
#     is_self_evaluated = models.BooleanField(default=False)
#     file_solution = models.FileField(blank=True, null=True)
#     test_solution = models.TextField(blank=True)
#     course = models.ForeignKey(Course, on_delete=models.CASCADE)
