name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: 'server.test_settings'
      DEBUG: 1
      DATABASE_PASSWORD: password
      DATABASE_NAME: elearning
      DATABASE_HOST: 127.0.0.1
      DATABASE_USER: postgres
      GAR_URL: http://0.0.0.0:8000

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          make sync-all-deps

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: pytest .

  e2e-test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: 'server.test_settings'
      DEBUG: 1
      DATABASE_PASSWORD: password
      DATABASE_NAME: elearning
      DATABASE_HOST: 127.0.0.1
      DATABASE_USER: postgres
      GAR_URL: http://0.0.0.0:8000

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          make sync-all-deps

      - name: Start application
        run: |
          make run-for-cypress & sleep 10     
      # Give the server some time to start up

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Node.js dependencies
        run: npm ci

      - name: Cypress run 
        uses: cypress-io/github-action@v5.5.1
        with: 
          browser: chrome
          start: make cypress-run
          wait-on: http://0.0.0.0:8000
          wait-on-timeout: 120

  notify:
    needs: [test, e2e-test]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: 'Hello hello! We have CI results for ${{ github.repository }} :tada:'
          SLACK_COLOR: ${{ job.status }}
          SLACK_LINK_NAMES: true
          SLACK_MESSAGE: |
            
            *Test Status*: ${{ needs.test.result }}
            *e2e Status*: ${{ needs.e2e-test.result }}

            *commit*: ${{ github.sha }}
            *branch*: ${{ github.ref }}
