name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: 'server.test_settings'
      DEBUG: 1
      DATABASE_PASSWORD: password
      DATABASE_NAME: elearning
      DATABASE_HOST: 127.0.0.1
      DATABASE_USER: postgres
      GAR_URL: http://0.0.0.0:8000

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          make sync-all-deps

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: pytest .

  notify:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          text: ${{ job.status }} | ${{ github.repository }} - ${{ github.workflow }} - ${{ github.sha }} - ${{ github.ref }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}