name: Platform CI/CD

on:
  push:
    branches:
      - develop


jobs:
  tests:
    env:
      DJANGO_SETTINGS_MODULE: 'server.settings'
      DEBUG: 1
      DATABASE_PASSWORD: password
      DATABASE_NAME: elearning
      DATABASE_HOST: 0.0.0.0
      DATABASE_USER: postgres

    runs-on: ubuntu-latest
    services:
      postgres: 
        image: postgres:latest
        env:
          POSTGRES_DB: elearning
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Cache Python Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        run: |
          make sync-all-deps

      - name: Run Migrations (locally - workflow)
        run: |
          python manage.py migrate

      - name: Run Unit Tests
        run: pytest .

  notify:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: ':robot: CI results for ${{ github.repository }}'
          SLACK_COLOR: ${{ needs.tests.result }}
          SLACK_LINK_NAMES: true
          SLACK_MESSAGE: |
            *Tests results:*
            - unit-tests : ${{ needs.tests.result }}

            *commit*: ${{ github.sha }}
            *branch*: ${{ github.ref }}
